before_script:
  - npm install -g grunt-cli
  - npm install
  - cp config/config.travis.js config/config.js
  - cp public/js/lib/bootstrap-material-design/less/_variables.less config/_variables.less
  - cd extensions/keplergl/browser
  - npm install
  - cd ../../..
  - cd public/js/lib/bootstrap-material-design
  - npm install
  - cd ../../../..
#  - grunt production
language: node_js
node_js:
  - "8"
#cache:
#  directories:
#    - node_modules
